# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Garri\Desktop\Dofus3Click

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Garri\Desktop\Dofus3Click

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	echo >nul && "C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache\fast: edit_cache
.PHONY : edit_cache\fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	echo >nul && "C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache\fast: rebuild_cache
.PHONY : rebuild_cache\fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Garri\Desktop\Dofus3Click\CMakeFiles C:\Users\Garri\Desktop\Dofus3Click\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Garri\Desktop\Dofus3Click\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean
.PHONY : clean

# The main clean target
clean\fast: clean
.PHONY : clean\fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall\fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Dofus3Click

# Build rule for target.
Dofus3Click: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) Dofus3Click
.PHONY : Dofus3Click

# fast build rule for target.
Dofus3Click\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dofus3Click.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Dofus3Click.dir\build
.PHONY : Dofus3Click\fast

src\basicOperations.obj: src\basicOperations.cpp.obj
.PHONY : src\basicOperations.obj

# target to build an object file
src\basicOperations.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dofus3Click.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Dofus3Click.dir\src\basicOperations.cpp.obj
.PHONY : src\basicOperations.cpp.obj

src\basicOperations.i: src\basicOperations.cpp.i
.PHONY : src\basicOperations.i

# target to preprocess a source file
src\basicOperations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dofus3Click.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Dofus3Click.dir\src\basicOperations.cpp.i
.PHONY : src\basicOperations.cpp.i

src\basicOperations.s: src\basicOperations.cpp.s
.PHONY : src\basicOperations.s

# target to generate assembly for a file
src\basicOperations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dofus3Click.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Dofus3Click.dir\src\basicOperations.cpp.s
.PHONY : src\basicOperations.cpp.s

src\main.obj: src\main.cpp.obj
.PHONY : src\main.obj

# target to build an object file
src\main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dofus3Click.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Dofus3Click.dir\src\main.cpp.obj
.PHONY : src\main.cpp.obj

src\main.i: src\main.cpp.i
.PHONY : src\main.i

# target to preprocess a source file
src\main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dofus3Click.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Dofus3Click.dir\src\main.cpp.i
.PHONY : src\main.cpp.i

src\main.s: src\main.cpp.s
.PHONY : src\main.s

# target to generate assembly for a file
src\main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dofus3Click.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Dofus3Click.dir\src\main.cpp.s
.PHONY : src\main.cpp.s

src\system\actualTime.obj: src\system\actualTime.cpp.obj
.PHONY : src\system\actualTime.obj

# target to build an object file
src\system\actualTime.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dofus3Click.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Dofus3Click.dir\src\system\actualTime.cpp.obj
.PHONY : src\system\actualTime.cpp.obj

src\system\actualTime.i: src\system\actualTime.cpp.i
.PHONY : src\system\actualTime.i

# target to preprocess a source file
src\system\actualTime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dofus3Click.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Dofus3Click.dir\src\system\actualTime.cpp.i
.PHONY : src\system\actualTime.cpp.i

src\system\actualTime.s: src\system\actualTime.cpp.s
.PHONY : src\system\actualTime.s

# target to generate assembly for a file
src\system\actualTime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dofus3Click.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Dofus3Click.dir\src\system\actualTime.cpp.s
.PHONY : src\system\actualTime.cpp.s

src\system\file.obj: src\system\file.cpp.obj
.PHONY : src\system\file.obj

# target to build an object file
src\system\file.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dofus3Click.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Dofus3Click.dir\src\system\file.cpp.obj
.PHONY : src\system\file.cpp.obj

src\system\file.i: src\system\file.cpp.i
.PHONY : src\system\file.i

# target to preprocess a source file
src\system\file.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dofus3Click.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Dofus3Click.dir\src\system\file.cpp.i
.PHONY : src\system\file.cpp.i

src\system\file.s: src\system\file.cpp.s
.PHONY : src\system\file.s

# target to generate assembly for a file
src\system\file.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dofus3Click.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Dofus3Click.dir\src\system\file.cpp.s
.PHONY : src\system\file.cpp.s

src\system\inputs.obj: src\system\inputs.cpp.obj
.PHONY : src\system\inputs.obj

# target to build an object file
src\system\inputs.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dofus3Click.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Dofus3Click.dir\src\system\inputs.cpp.obj
.PHONY : src\system\inputs.cpp.obj

src\system\inputs.i: src\system\inputs.cpp.i
.PHONY : src\system\inputs.i

# target to preprocess a source file
src\system\inputs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dofus3Click.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Dofus3Click.dir\src\system\inputs.cpp.i
.PHONY : src\system\inputs.cpp.i

src\system\inputs.s: src\system\inputs.cpp.s
.PHONY : src\system\inputs.s

# target to generate assembly for a file
src\system\inputs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dofus3Click.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Dofus3Click.dir\src\system\inputs.cpp.s
.PHONY : src\system\inputs.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... Dofus3Click
	@echo ... src/basicOperations.obj
	@echo ... src/basicOperations.i
	@echo ... src/basicOperations.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/system/actualTime.obj
	@echo ... src/system/actualTime.i
	@echo ... src/system/actualTime.s
	@echo ... src/system/file.obj
	@echo ... src/system/file.i
	@echo ... src/system/file.s
	@echo ... src/system/inputs.obj
	@echo ... src/system/inputs.i
	@echo ... src/system/inputs.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

